// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import loadConfigs from './src/common/libs/loadConfigs';
import { Config } from 'src/types/config';

const config = loadConfigs();

export function buildDatabaseUrl(config: Record<Config, string>): string {
  return `mysql://${config.DATABASE_USER}:${encodeURIComponent(config.DATABASE_PASSWORD)}@${config.DATABASE_HOST}:${config.DATABASE_PORT}/${config.DATABASE_NAME}`;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: buildDatabaseUrl(config),
  },
});
